services:
  ml-service:
    build: .
    ports:
      - "8888:8888"  # JupyterLab
      - "8000:8000"  # FastAPI
    volumes:
      - .:/app
      - ./notebooks:/app/notebooks:wr  # Asegura que notebooks est치 montado
      - /tmp/.X11-unix:/tmp/.X11-unix  # Necesario para renderizado gr치fico
    environment:
      - DISPLAY=$DISPLAY  # Para permitir renderizado gr치fico
    devices:
      - /dev/dri:/dev/dri  # Pasa los dispositivos de renderizado gr치fico (Intel GPU)
    deploy:
      resources:
        reservations:
          devices: []  # Elimina las referencias a NVIDIA
    networks:
      - app-network
  
  networks:
    app-network:
      external: true
